### ISSUE TITLE
Disponibilidad de AKS

### ISSUE THREAD

**Issue by mendrugory** [MicrosoftDocs/azure-docs.es-es#108]
¿El resto de regiones se habilitarán cuando se salga de la fase preliminar?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 18e73ba6-a06d-9bc4-fef6-6ece8a166e84
* Version Independent ID: a9efcfab-f4c5-969b-4cd4-aa86ebd80534
* Content: [Disponibilidad de regiones y cuotas en Azure Container Service (AKS)](https://docs.microsoft.com/es-es/azure/aks/container-service-quotas)
* Content Source: [articles/aks/container-service-quotas.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/live/articles/aks/container-service-quotas.md)
* Service: **container-service**
* GitHub Login: @david-stanford
* Microsoft Alias: **dastanfo**

**Comment by CeciAc** [comment]
Hola, @mendrugory 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Proporcionar comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs 

@SunnyDeng
