### ISSUE TITLE
Funcionamiento distinto en Windows 10 y Windows 8.1

### ISSUE THREAD

**Issue by soydlopez** [MicrosoftDocs/azure-docs.es-es#109]
o.
Tengo habilitado la configuración Híbrida y en Windows 10 me funciona distinto que en los equipos Windows 8.1.
Tengo un usuario, (usuario1) con el UPN local (dominio.local) se ha configurado un id alternativo en el AD Connect el campo email (usuario1@dominiopublico.com). 
En windows 10 si iniciamos sesion con usuario1 no funcina el SSo y hay que insertar la calve para acceder al OWA, de Office365.
En windows 8.1 si iniciamos con el mismo usuario, usuario1 el acceso al OWA no pide la password y accede sin problemas.
Para que funcione en Windows 10, hace falta iniciar sesion en el equipo con un usuario del AD local que se le haya agregado el UPN publico al usuario. en este caso el Windows 10 si funciona el SSo.

Me gustaria saber si hay algo mal que estamos realizand
Saludos.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 72cdc251-618a-e84e-f40d-960b0ac69f99
* Version Independent ID: 8cbaba3c-e883-2c71-28fb-f88db3fcaf7d
* Content: [Configuración de dispositivos híbridos unidos a Azure Active Directory](https://docs.microsoft.com/es-es/azure/active-directory/device-management-hybrid-azuread-joined-devices-setup)
* Content Source: [articles/active-directory/device-management-hybrid-azuread-joined-devices-setup.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/live/articles/active-directory/device-management-hybrid-azuread-joined-devices-setup.md)
* Service: **active-directory**
* GitHub Login: @MarkusVi
* Microsoft Alias: **markvi**

**Comment by CeciAc** [comment]
Hola, @soydlopez: 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón de proporcionar "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs 

@SunnyDeng
