### ISSUE TITLE
Bug in dashboard URL for kubernetes

### ISSUE THREAD

**Issue by joseluissanchezgracia** [MicrosoftDocs/azure-docs.es-es#12]
The doc says that the URL for browsing to kubernetes dashboard is 
http://localhost: 8001/interfaz de usuario.
Fail. 
It is http://localhost: 8001/ui

**Comment by SunnyDeng** [comment]
@joseluissanchezgracia if this issue still repo, could you point me the specific articles URL?

**Comment by joseluissanchezgracia** [comment]
@SunnyDeng It seems the doc has changed and there is no specific URL to browser kubernetes dashboard (now doc explains how to connect by using "az acs kubernetes browse" command so I think this issue can be closed.

**Comment by SunnyDeng** [comment]
Thanks. Closed.
