### ISSUE TITLE
Format Fix

### ISSUE THREAD

**Issue by pepenotti** [MicrosoftDocs/azure-docs.es-es#127]
"requisito" a  "Requisito"
https://docs.microsoft.com/es-es/azure/sql-database/saas-dbpertenant-get-started-deploy#prerequisites

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 2ede0bd6-400a-50ea-1ca0-43754c16c1f5
* Version Independent ID: 621395e7-83a4-bbb5-9b8d-2d8beaed2d9b
* Content: [Tutorial de la aplicación de SaaS de base de datos por inquilino: Azure SQL Database](https://docs.microsoft.com/es-es/azure/sql-database/saas-dbpertenant-get-started-deploy#prerequisites)
* Content Source: [articles/sql-database/saas-dbpertenant-get-started-deploy.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/live/articles/sql-database/saas-dbpertenant-get-started-deploy.md)
* Service: **sql-database**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by gosali** [comment]
Hello, @pepenotti , 

Thank you for your feedback. 

 We are actively reviewing your comments and will get back to you soon. 

Kind regards, 
Microsoft DOCS International Team

**Comment by MightyPen** [comment]
@pepenotti Prompted by this GitHub Issue that you posted, today I looked at the es-es translation of the original English en-us source article. I do see the mistake that you are pointing out, involving a lowercase letter 'r' which should be uppercase 'R'.
Localization into other languages is profoundly expensive and time consuming, and it is very difficult to get the entire translation perfect. I do not work on the Localization team, and my understanding of their complex processes is limited. Today I am filing a bug report about this mistake to the Localization team, and thus I will also Close this GitHub Issue and let the bug take over. I cannot say how long it might be before the Localization system can address the problem.
Thank you for bringing this mistake to our attention.

**Comment by MightyPen** [comment]
#please-close

**Comment by SunnyDeng** [comment]
Hi @MightyPen thanks for your suppose for loc. Loc team is monitoring the GITHUG ISSUE as daily basis. The fix of this one is not hard. @gosali is on top of it and will respond when fix.

**Comment by SunnyDeng** [comment]
Thus NO need to close.

**Comment by LisandroSu** [comment]
Hola, @pepenotti :

Gracias por sus   comentarios.

El equipo lingüístico ha   revisado las sugerencias y las ha aceptado. Hemos implementado sus   comentarios y los hemos publicado en los artículos actualizados del sitio de   Docs en las siguientes páginas: [Tutorial de la aplicación de SaaS de base de datos por inquilino: Azure SQL Database](https://docs.microsoft.com/es-es/azure/sql-database/saas-dbpertenant-get-started-deploy#prerequisites).

Apreciamos su colaboración y   le animamos a seguir enviándonos comentarios.

Atentamente,
Equipo internacional de   Microsoft Docs
