### ISSUE TITLE
No funciona correctamente

### ISSUE THREAD

**Issue by SleepDays** [MicrosoftDocs/azure-docs.es-es#128]
Al menos en mi Xiaomi Redmi Note 4 me pide el Pin, se le pone y lo vuelve a pedir reiteradamente siendo este correcto. Cuando pongo uno erroneo lo dice pero siendo el correcto algo mal habra ahi. Y por eso se queda inservible la app... es una pena.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: fd8c41de-1751-6ecd-24b9-ab687f7ae467
* Version Independent ID: 11d17688-b87e-f681-cf84-ce90f93e26ce
* Content: [Inicio de sesión en Microsoft Authenticator con el teléfono: cuentas de Azure y Microsoft](https://docs.microsoft.com/es-es/azure/active-directory/authentication/end-user/current/microsoft-authenticator-app-phone-signin-faq)
* Content Source: [articles/active-directory/authentication/end-user/current/microsoft-authenticator-app-phone-signin-faq.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/live/articles/active-directory/authentication/end-user/current/microsoft-authenticator-app-phone-signin-faq.md)
* Service: **multi-factor-authentication**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by gosali** [comment]
Hola, @SleepDays :  

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación.  

Registre los comentarios de su producto mediante el botón "Proporcionar comentarios sobre el producto" en la parte inferior de la página de DOCS.  

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal.  
Apreciamos su contribución a nuestros artículos.   

CC @SunnyDeng 
Atentamente,  
Equipo internacional de Microsoft Docs
