### ISSUE TITLE
No se pueden visualizar los datos

### ISSUE THREAD

**Issue by fede3mmanuel** [MicrosoftDocs/azure-docs.es-es#129]
Parece que se guardan los datos, pero no tienen extensión, y por lo tanto no se pueden abrir

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ vinculación de problemas de GitHub.*

* ID: 3b0bc375-145f-3e45-e1e9-1869e183a4a3
* Version Independent ID: 8dc4d773-0a92-31de-6ce4-4a118d552f6a
* Content: [Procedimiento para guardar los mensajes de IoT Hub en el almacenamiento de datos de Azure](https://docs.microsoft.com/es-mx/azure/iot-hub/iot-hub-store-data-in-azure-table-storage)
* Content Source: [articles/iot-hub/iot-hub-store-data-in-azure-table-storage.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/live/articles/iot-hub/iot-hub-store-data-in-azure-table-storage.md)
* Service: **iot-hub**
* GitHub Login: @rangv
* Microsoft Alias: **rangv**

**Comment by LisandroSu** [comment]
Hola, @fede3mmanuel :

Agradecemos enormemente su   colaboración. Nuestro equipo solo puede responder a comentarios relacionados   con la documentación.
 
Registre los comentarios de su   producto mediante el botón "Proporcionar comentarios sobre el producto" en la parte inferior de la página de DOCS.
 
Si tiene comentarios   relacionados con la documentación, regístrelos a través de este canal.
 
Apreciamos su contribución a nuestros artículos.

Atentamente,
Equipo internacional de   Microsoft Docs
