### ISSUE TITLE
Error: Unexpected token H in JSON at position 0 

### ISSUE THREAD

**Issue by YeyoCoder** [MicrosoftDocs/azure-docs.es-es#130]
I tried to deploy locally following the guide [Deploy the Remote Monitoring solution accelerator locally](https://docs.microsoft.com/es-es/azure/iot-accelerators/iot-accelerators-remote-monitoring-deploy-local)  **but I get the following problem **:  

- From Chrome
![image](https://user-images.githubusercontent.com/39103825/42849152-b5143cd0-89e7-11e8-8747-df33f00a7e18.png)

- From Edge
![image](https://user-images.githubusercontent.com/39103825/42849195-df65276a-89e7-11e8-8d5f-0caa6f716238.png)

- From Postman
![image](https://user-images.githubusercontent.com/39103825/42849312-48736474-89e8-11e8-89d4-f6ed6162eb78.png)
![image](https://user-images.githubusercontent.com/39103825/42849290-31b22586-89e8-11e8-8c3d-1d178c55f7fe.png)

  
Then I deploy from [azureiotsolutions.com](https://www.azureiotsolutions.com/Accelerators) and it work!  

**Why I can´t deploy it locally** following the instructions of [Deploy the Remote Monitoring solution accelerator locally](https://docs.microsoft.com/es-es/azure/iot-accelerators/iot-accelerators-remote-monitoring-deploy-local) as deployed with [azureiotsolutions.com](https://www.azureiotsolutions.com/Accelerators)**?**  

Any one have deployed this monitoring solution **locally** following the steps of [Deploy the Remote Monitoring solution accelerator locally](https://docs.microsoft.com/es-es/azure/iot-accelerators/iot-accelerators-remote-monitoring-deploy-local)**?**  

Can this be deploy using the **Free tier of the IoTHub** and the **Cosmos DB Emulator?** 
  

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 19039245-3c01-72b1-b90a-de21be4d688e
* Version Independent ID: c0af7f85-3a2a-ae20-93b3-cbf2b2851230
* Content: [Implementación local de la solución de supervisión remota: Azure](https://docs.microsoft.com/es-es/azure/iot-accelerators/iot-accelerators-remote-monitoring-deploy-local#next-steps)
* Content Source: [articles/iot-accelerators/iot-accelerators-remote-monitoring-deploy-local.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/live/articles/iot-accelerators/iot-accelerators-remote-monitoring-deploy-local.md)
* Service: **iot-accelerators**
* GitHub Login: @dominicbetts
* Microsoft Alias: **dobett**

**Comment by LisandroSu** [comment]
Hello, @YeyoCoder , 
 
Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 
 
If you have any feedback related to the documentation, please feel free to log it through this channel. 
We truly appreciate your contribution to our articles.  
 
Kind regards, 
Microsoft DOCS International Team
