### ISSUE TITLE
Esto no me funciona

### ISSUE THREAD

**Issue by walleSenpai** [MicrosoftDocs/azure-docs.es-es#132]
Estoy intenando crear una máquina virtual con un disco administrado y el script no me funciona y me salta el error siguiente : 

New-AzureRmVM : Changing property 'osDisk.osType' is not allowed.
ErrorCode: PropertyChangeNotAllowed
ErrorMessage: Changing property 'osDisk.osType' is not allowed.
StatusCode: 409
ReasonPhrase: Conflict
OperationID : 778c8aea-a893-4dbc-a33c-21bd533d690f
En C:\Users\gpedra\Desktop\aixecarVmDiscoCopia.ps1: 52 Carácter: 1
+ New-AzureRmVM -VM $VirtualMachine -ResourceGroupName $resourceGroupNa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmVM], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.NewAzureVMCommand

Mi script es el siguiente :

#Provide the subscription Id
$subscriptionId ='XXXXX'

#Provide the name of your resource group
$resourceGroupName ='XXXXX'

#Provide the name of the snapshot that will be used to create OS disk
$snapshotName ='test-Snap'

#Provide the name of the OS disk that will be created using the snapshot
$osDiskName ='TestTraslado3'

#Provide the name of an existing virtual network where virtual machine will be created
$virtualNetworkName ='TestTraslado2'

#Provide the name of the virtual machine
$virtualMachineName ='TestTraslado2'

#Provide the size of the virtual machine
#e.g. Standard_DS3
#Get all the vm sizes in a region using below script:
#e.g. Get-AzureRmVMSize -Location westus
$virtualMachineSize = 'Standard_D4s_v3'

#Set the context to the subscription Id where Managed Disk will be created
Select-AzureRmSubscription -SubscriptionId $SubscriptionId

$snapshot = Get-AzureRmSnapshot -ResourceGroupName $resourceGroupName -SnapshotName $snapshotName
 
$diskConfig = New-AzureRmDiskConfig -Location $snapshot.Location -SourceResourceId $snapshot.Id -CreateOption Copy
 
$disk = New-AzureRmDisk -Disk $diskConfig -ResourceGroupName $resourceGroupName -DiskName $osDiskName

#Initialize virtual machine configuration
$VirtualMachine = New-AzureRmVMConfig -VMName $virtualMachineName -VMSize $virtualMachineSize

#Use the Managed Disk Resource Id to attach it to the virtual machine. Please change the OS type to linux if OS disk has linux OS
$VirtualMachine = Set-AzureRmVMOSDisk -VM $VirtualMachine -ManagedDiskId $disk.Id -CreateOption Attach -Linux

#Create a public IP for the VM
$publicIp = New-AzureRmPublicIpAddress -Name ($VirtualMachineName.ToLower()+'_ip') -ResourceGroupName $resourceGroupName -Location $snapshot.Location -AllocationMethod Dynamic

#Get the virtual network where virtual machine will be hosted
$vnet = Get-AzureRmVirtualNetwork -Name $virtualNetworkName -ResourceGroupName $resourceGroupName

# Create NIC in the first subnet of the virtual network
$nic = New-AzureRmNetworkInterface -Name ($VirtualMachineName.ToLower()+'_nic') -ResourceGroupName $resourceGroupName -Location $snapshot.Location -SubnetId $vnet.Subnets[0].Id -PublicIpAddressId $publicIp.Id

$VirtualMachine = Add-AzureRmVMNetworkInterface -VM $VirtualMachine -Id $nic.Id

#Create the virtual machine with Managed Disk
New-AzureRmVM -VM $VirtualMachine -ResourceGroupName $resourceGroupName -Location $snapshot.Location

No entiendo que puede estar pasando. alguna ayuda?

Gracias :D

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 8712c031-cf75-9523-0d70-2e33e7a3ca1d
* Version Independent ID: 87134f0c-b50a-a95b-a2e4-bb2eccd8da2b
* Content: [Script de Azure PowerShell de Azure de ejemplo: creación de una máquina virtual conectando un disco administrado como disco del SO](https://docs.microsoft.com/es-es/azure/virtual-machines/scripts/virtual-machines-windows-powershell-sample-create-vm-from-managed-os-disks)
* Content Source: [articles/virtual-machines/scripts/virtual-machines-windows-powershell-sample-create-vm-from-managed-os-disks.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/live/articles/virtual-machines/scripts/virtual-machines-windows-powershell-sample-create-vm-from-managed-os-disks.md)
* Service: **virtual-machines-windows**
* GitHub Login: @ramankum
* Microsoft Alias: **ramankum**

**Comment by LisandroSu** [comment]
Hola, @walleSenpai 

Agradecemos enormemente su   colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación.
 
Registre los comentarios de su producto mediante el botón "Proporcionar comentarios sobre el producto" en la parte inferior de la página de DOCS.
 
Si tiene comentarios   relacionados con la documentación, regístrelos a través de este canal.
Apreciamos su contribución a nuestros artículos.
 
Atentamente,
Equipo internacional de Microsoft Docs
