### ISSUE TITLE
certificados solo para PaaS

### ISSUE THREAD

**Issue by Stech01** [MicrosoftDocs/azure-docs.es-es#134]
Hola ya tengo implementado Azure Stack  y ahora requiero habilitar PaaS, que línea de instrucción es la sugerida para solamente crear la solicitud de firma para certificados PaaS? gracias.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 0b5d2a91-d8f6-2594-dab8-38fe25b303c7
* Version Independent ID: 0beba5f9-90fc-9e9f-63b6-474e5a0e3736
* Content: [Generación de certificados de infraestructura de clave pública de Azure Stack para la implementación de sistemas integrados de Azure Stack](https://docs.microsoft.com/es-es/azure/azure-stack/azure-stack-get-pki-certs)
* Content Source: [articles/azure-stack/azure-stack-get-pki-certs.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/live/articles/azure-stack/azure-stack-get-pki-certs.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by LisandroSu** [comment]
Hola, @Stech01 :

Agradecemos enormemente su   colaboración. Nuestro equipo solo puede responder a comentarios relacionados   con la documentación.

Registre los comentarios de su   producto mediante el botón "Proporcionar comentarios   sobre el producto" en la parte inferior de la página de DOCS.
 
Si tiene comentarios   relacionados con la documentación, regístrelos a través de este canal.
Apreciamos su contribución a nuestros artículos.
 
Atentamente,
Equipo internacional de   Microsoft Docs
