### ISSUE TITLE
Problemas al trabajar con datos de entrada o salida nulos en la extensión de Python

### ISSUE THREAD

**Issue by rnavarromatesanz** [MicrosoftDocs/azure-docs.es-es#135]
Hola,

A la hora de introducir valores nulos al codigo Python no lo gestiona correctametne, por ejemplo al intentar introducir una columna de tipo int con uno o varios campos vacios, me lo transforma en un 0 no en un NaN.

Podrían indicarme cual puede ser el problema, ya que sin hacer nada sobre la columna, el valor retornado es 0.

Un saludo
Roberto

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: b16aab5f-58fa-9ecb-8939-25c08b32626e
* Version Independent ID: 1d0ae4db-7870-2716-b91f-88f8f0e2d81d
* Content: [Extensión de los scripts de U-SQL con Python en Azure Data Lake Analytics](https://docs.microsoft.com/es-es/azure/data-lake-analytics/data-lake-analytics-u-sql-python-extensions)
* Content Source: [articles/data-lake-analytics/data-lake-analytics-u-sql-python-extensions.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/live/articles/data-lake-analytics/data-lake-analytics-u-sql-python-extensions.md)
* Service: **data-lake-analytics**
* GitHub Login: @saveenr
* Microsoft Alias: **saveenr**

**Comment by LisandroSu** [comment]
Hola, @rnavarromatesanz 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
