### ISSUE TITLE
Is there a way to register an app via PowerShell, CLI or API REST?

### ISSUE THREAD

**Issue by 0GiS0** [MicrosoftDocs/azure-docs.es-es#138]
I need to automate this process but I didn't see if there is a way to register apps via PS, CLI or API REST.

Thanks!

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: fcf76a42-4ecb-63c9-8ca0-40af417006d7
* Version Independent ID: 34c4f58e-a6a9-ab8c-0721-c4b8c5e0248b
* Content: [Tutorial: Habilitación de una aplicación web para autenticarse con cuentas mediante Azure Active Directory B2C](https://docs.microsoft.com/es-es/azure/active-directory-b2c/active-directory-b2c-tutorials-web-app)
* Content Source: [articles/active-directory-b2c/active-directory-b2c-tutorials-web-app.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/live/articles/active-directory-b2c/active-directory-b2c-tutorials-web-app.md)
* Service: **active-directory**
* GitHub Login: @davidmu1
* Microsoft Alias: **davidmu**

**Comment by LisandroSu** [comment]
Hello, @0GiS0 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
