### ISSUE TITLE
Who to query a vnet-rule

### ISSUE THREAD

**Issue by ediazrod** [MicrosoftDocs/azure-docs.es-es#145]
I like to search all the databases with a vnet-rule on it. but I see the option.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: ac94b233-b387-fd3e-1942-83044d29fc80
* Version Independent ID: f6554623-0d7b-f4cc-fc00-8616010f0714
* Content: [Consultas avanzadas de Azure Resource Graph](https://docs.microsoft.com/es-es/azure/governance/resource-graph/samples/advanced)
* Content Source: [articles/governance/resource-graph/samples/advanced.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/live/articles/governance/resource-graph/samples/advanced.md)
* Service: **resource-graph**
* GitHub Login: @DCtheGeek
* Microsoft Alias: **dacoulte**

**Comment by DCtheGeek** [comment]
@ediazrod Thanks for the question!  I don't see vnet details on a server or database object, assuming you mean Azure SQL Server. The best way to request this would be to post on [UserVoice](https://feedback.azure.com/forums/915958-azure-governance). You can also use the Feedback control in Azure portal from the Resource Graph page and the PG will provide query assistance.

@MicrosoftDocs/azure-cxp-triage Please assign to me, label as 'product-question', and #please-close.
