### ISSUE TITLE
Las instrucciones para almacenamiento estático no funcionan (en Linux).

### ISSUE THREAD

**Issue by JJ** [MicrosoftDocs/azure-docs.es-es#155]
Usando `az`, última versión, esta línea no funciona:

    az storage blob upload-batch -s <SOURCE_PATH> -d $web --account-name <ACCOUNT_NAME>

El problema es que `$web` se interpreta como una variable de shell. Como está vacía, produce este error:

    az storage blob upload-batch: error: argument --destination/-d: expected one argument

He intentado también "$web" y "\$web" como argumento, con el mismo resultado. Usar simplemente "web" (previa creación del contenedor) deja subir los ficheros, pero no funciona. ¿Alguna idea de cómo solucionarlo?

**Comment by CeciAc** [comment]
Hola, @JJ 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
