### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by DavidGanduglia** [MicrosoftDocs/azure-docs.es-es#156]
Both projects run properly, but when trying to call the API from the Web App, it throws the exception "The request was aborted: Could not create SSL/TLS secure channel."
I'm using Windows 7, shall I add something to the example?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: df26c5f6-63b9-d281-5724-c0731546b087
* Version Independent ID: 239bf87c-fcf0-b35e-744d-fecbb55501e4
* Content: [Tutorial: Conceder acceso a una API web de ASP.NET desde una aplicación web mediante Azure Active Directory B2C](https://docs.microsoft.com/es-es/azure/active-directory-b2c/active-directory-b2c-tutorials-web-api)
* Content Source: [articles/active-directory-b2c/active-directory-b2c-tutorials-web-api.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/live/articles/active-directory-b2c/active-directory-b2c-tutorials-web-api.md)
* Service: **active-directory**
* GitHub Login: @davidmu1
* Microsoft Alias: **davidmu**

**Comment by CeciAc** [comment]
Hello, @DavidGanduglia,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
