### ISSUE TITLE
When will it be implemented? In the XXII century?

### ISSUE THREAD

**Issue by arturosoler** [MicrosoftDocs/azure-docs.es-es#157]
For months, almost a year, you announce us that integration in the Office 365 message center, and at least here in Spain and in my company, at the end of 1918 it is not activated yet.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 22b21ab5-ea75-2f79-f497-4dfd2235fa52
* Version Independent ID: a05c8fd9-f1fb-f860-678e-61445886daf8
* Content: [Habilitación de la integración de conexiones de LinkedIn en Azure Active Directory](https://docs.microsoft.com/es-es/azure/active-directory/users-groups-roles/linkedin-integration)
* Content Source: [articles/active-directory/users-groups-roles/linkedin-integration.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/live/articles/active-directory/users-groups-roles/linkedin-integration.md)
* Service: **active-directory**
* GitHub Login: @curtand
* Microsoft Alias: **curtand**

**Comment by CeciAc** [comment]
Hello, @arturosoler 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
