### ISSUE TITLE
TSI Walkthough Video 

### ISSUE THREAD

**Issue by pvirgili** [MicrosoftDocs/azure-docs.es-es#161]
Hi folks,
I've been watching the TSI walkthrough video and in minute 10:32 the presenter had to return to read the TSI  documentation and even with no comments at all. After 2+ minutes in silence he continued with the powerpoint "as nothing happened here". I think is a better idea to edit the video to avoid that part.
Best.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: efcc6b18-da08-c3cd-fee0-5f6a83108901
* Version Independent ID: 47c34837-e3ba-0128-70ef-f276d53d35e1
* Content: [Introducción a Azure Time Series Insights: ¿Qué es Azure Time Series Insights?](https://docs.microsoft.com/es-es/azure/time-series-insights/time-series-insights-overview)
* Content Source: [articles/time-series-insights/time-series-insights-overview.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/live/articles/time-series-insights/time-series-insights-overview.md)
* Service: **time-series-insights**
* GitHub Login: @ashannon7
* Microsoft Alias: **anshan**

**Comment by LisandroSu** [comment]
Hello, @pvirgili 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #21667](https://github.com/MicrosoftDocs/azure-docs/issues/21667) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @pvirgili 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/21667.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
