### ISSUE TITLE
Gracias por el artículo

### ISSUE THREAD

**Issue by Nessia** [MicrosoftDocs/azure-docs.es-es#173]
Una pequeña corrección, al menos en Spark 1.6 ya había DataFrames. Un saludo

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 9fe05fbb-40a8-d8f1-c03e-6f2a1701c6f1
* Version Independent ID: 03d25fb4-4c08-a573-a307-ee638a30658c
* Content: [Optimización de trabajos de Spark para mejorar el rendimiento en Azure HDInsight](https://docs.microsoft.com/es-es/azure/hdinsight/spark/apache-spark-perf)
* Content Source: [articles/hdinsight/spark/apache-spark-perf.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/live/articles/hdinsight/spark/apache-spark-perf.md)
* Service: **hdinsight**
* GitHub Login: @maxluk
* Microsoft Alias: **maxluk**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #21572](https://github.com/MicrosoftDocs/azure-docs/issues/21572) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hola, @Nessia 

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original. 
Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/MicrosoftDocs/azure-docs/issues/21572. 
Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
