### ISSUE TITLE
Can't deploy low priority VMSS from the Portal

### ISSUE THREAD

**Issue by carlfm01** [MicrosoftDocs/azure-docs.es-es#215]
I'm trying to deploy Standard A0 on a VMSS, but can't enable low priority, tried with Linux and Windows, also with different locations.
¿Any ideas?
Thanks.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: a1bd5076-fe52-cfca-4173-dec861167812
* Version Independent ID: 0122fff1-79e0-446c-00a4-85248a21b6dc
* Content: [Creación de un conjunto de escalado de Azure que usa máquinas virtuales de prioridad baja (versión preliminar)](https://docs.microsoft.com/es-es/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-use-low-priority)
* Content Source: [articles/virtual-machine-scale-sets/virtual-machine-scale-sets-use-low-priority.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/live/articles/virtual-machine-scale-sets/virtual-machine-scale-sets-use-low-priority.md)
* Service: **virtual-machine-scale-sets**
* GitHub Login: @mmccrory
* Microsoft Alias: **memccror**

**Comment by CeciAc** [comment]
Hello, @carlfm01

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
