### ISSUE TITLE
Activar Apagado automatico de las maquinas Virtuales

### ISSUE THREAD

**Issue by JuanCarlosHerreraBlandon** [MicrosoftDocs/azure-docs.es-es#245]
Buen dia 

Debi utilizar este proceso, ya que en la opcion de la categoria operaciones de la maquina virtual de Windows 10 no me estaba dejando desactivar el apagado automatico. Ya que mi maquina virtual despues de cierto tiempo se apagaba. Debemos registrar dos proveedores de servicio que son

Microsoft.DevTestLab y Microsoft.Scheduler 

Con estos dos servicios ya podemos configurar la maquina virtual para que no se apague automaticamente

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 107576e7-75ca-e4f7-34df-04f4992f1e21
* Version Independent ID: 64fbc1cd-065b-a4a6-7324-60ee8ca6f9ff
* Content: [Errores del registro de proveedor de recursos de Azure](https://docs.microsoft.com/es-es/azure/azure-resource-manager/resource-manager-register-provider-errors)
* Content Source: [articles/azure-resource-manager/resource-manager-register-provider-errors.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/live/articles/azure-resource-manager/resource-manager-register-provider-errors.md)
* Service: **azure-resource-manager**
* GitHub Login: @tfitzmac
* Microsoft Alias: **tomfitz**

**Comment by v-maudel** [comment]
Issue moved to [MicrosoftDocs/azure-docs #23138](https://github.com/MicrosoftDocs/azure-docs/issues/23138) via [**ZenHub**](https://www.zenhub.com/)

**Comment by v-maudel** [comment]
Hola, @JuanCarlosHerreraBlandon : 

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original. 
Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/MicrosoftDocs/azure-docs/issues/23138. 
Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
