### ISSUE TITLE
Puedo usar mis propias claves de cifrado? con llave HSM

### ISSUE THREAD

**Issue by acaceresssit** [MicrosoftDocs/azure-docs.es-es#255]
Puedo usar mis propias claves de cifrado? con llave HSM, esposible subir la llave HSM al keyVault para cifrado en reposo y no dejar por defecto.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 7c068a1f-f3bf-0ea8-ffff-c5626f6da77a
* Version Independent ID: 3adef505-3bd5-a55b-9697-1febe37d0a6a
* Content: [Cifrado de Azure Cosmos DB en reposo](https://docs.microsoft.com/es-es/azure/cosmos-db/database-encryption-at-rest)
* Content Source: [articles/cosmos-db/database-encryption-at-rest.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/live/articles/cosmos-db/database-encryption-at-rest.md)
* Service: **cosmos-db**
* GitHub Login: @rafats
* Microsoft Alias: **sngun**

**Comment by LisandroSu** [comment]
Hola, @acaceresssit 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
