### ISSUE TITLE
where do i put a password for the oracle vm?

### ISSUE THREAD

**Issue by gregdorian** [MicrosoftDocs/azure-docs.es-es#259]
in the step Automate database startup and shutdown needs a password? the password is:  OraPasswd1 ? it does not work!

https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/oracle/oracle-database-quick-create?view=sql-server-2016

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 279359a4-139a-ee4b-027b-4f43c538b90f
* Version Independent ID: 950014e2-2457-6045-eefd-865bd1c1fb76
* Content: [Creación de una base de datos Oracle en una VM de Azure](https://docs.microsoft.com/es-es/azure/virtual-machines/workloads/oracle/oracle-database-quick-create?view=sql-server-2016)
* Content Source: [articles/virtual-machines/workloads/oracle/oracle-database-quick-create.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/live/articles/virtual-machines/workloads/oracle/oracle-database-quick-create.md)
* Service: **virtual-machines-linux**
* GitHub Login: @romitgirdhar
* Microsoft Alias: **rogirdh**

**Comment by CeciAc** [comment]
Hello, @gregdorian 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

**Comment by gregdorian** [comment]
@CeciAc Si Cecilia en el documento no se encuentra que password se debe usar **Automate database startup and shutdown** indican hacer un sudo su - por eso creo que deberia modificar la pagina en ese lugar!!! ya que he tratado con OraPasswd1 y con el pass que cree la maquina virtual

**Comment by CeciAc** [comment]
Hola @gregdorian 
Por el canal que mencioné en el comentario anterior va a obtener asistencia a su problema. (mediante el botón "Comentarios sobre el producto")
De todos modos, voy enviar esto al autor de la documentación original para que lo revisen y determinen si la documentación deba modificarse.

Atentamente, 
Equipo internacional de Microsoft Docs

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #25074](https://github.com/MicrosoftDocs/azure-docs/issues/25074) via [**ZenHub**](https://www.zenhub.com/)
