### ISSUE TITLE
Link to download or install Apache Qpid Proton-PHP

### ISSUE THREAD

**Issue by Lotykun** [MicrosoftDocs/azure-docs.es-es#267]
I would like to know info about the AMQP client for PHP. There is no such info online, (or I have not find it). Concretely  if there is a composer install for the client library

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: d67bb512-809b-213d-2426-a9e0233dd8e0
* Version Independent ID: 46a123e8-ea1e-be6d-31fb-d158065d44f2
* Content: [Introducción a AMQP 1.0 en Azure Service Bus](https://docs.microsoft.com/es-es/azure/service-bus-messaging/service-bus-amqp-overview)
* Content Source: [articles/service-bus-messaging/service-bus-amqp-overview.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/live/articles/service-bus-messaging/service-bus-amqp-overview.md)
* Service: **service-bus-messaging**
* GitHub Login: @axisc
* Microsoft Alias: **aschhab**

**Comment by CeciAc** [comment]
Hello, @Lotykun 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
