### ISSUE TITLE
Detalle del contenido

### ISSUE THREAD

**Issue by UCdavidUC** [MicrosoftDocs/azure-docs.es-es#301]
En la sección Métodos y modelos de implementación para S2S, hace referencia a una conexión P2S, que corresponde al uso de autenticación mediante certificados nativos de Azure y autenticación RADIUS.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ vinculación de problemas de GitHub.*

* ID: 45d7ab31-fdf3-9b0f-1439-6a01fb257aab
* Version Independent ID: af13a45f-3061-2f0e-7452-b52d700b4805
* Content: [Azure VPN Gateway](https://docs.microsoft.com/es-mx/azure/vpn-gateway/vpn-gateway-about-vpngateways#V2V)
* Content Source: [articles/vpn-gateway/vpn-gateway-about-vpngateways.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/live/articles/vpn-gateway/vpn-gateway-about-vpngateways.md)
* Service: **vpn-gateway**
* GitHub Login: @cherylmc
* Microsoft Alias: **cherylmc**

**Comment by CeciAc** [comment]
Hola, @UCdavidUC 

Valoramos enormemente su comentario y estamos haciendo todo lo posible por mejorar su experiencia en docs.microsoft.com. No obstante, necesitamos más información para poder encargarnos de sus comentarios. ¿Puede proporcionar información más detallada y aclarar el comentario?

Atentamente,
Equipo internacional de Microsoft DOCS

**Comment by CeciAc** [comment]
Hola, @UCdavidUC 

Esta es una continuación de nuestro comentario anterior. Necesitamos más información para poder encargarnos de sus comentarios. ¿Puede proporcionar información más detallada y aclarar el comentario?

Atentamente,
Equipo internacional de Microsoft DOCS

**Comment by UCdavidUC** [comment]
Hola @CeciAc, 

Actualmente el título de la sección que hace referencia a autenticación en VPN es:

_"Métodos y modelos de implementación para S2S"_

Sin embargo, el contenido corresponde a mecanismos de autenticación Point-to-site (P2S), quizá el título de la sección correspondería a:

_"Métodos y modelos de implementación para P2S"_

Saludos,

**Comment by CeciAc** [comment]
Hola, @UCdavidUC 
Gracias por sus comentarios. 

Los revisaremos y nos pondremos en contacto con usted lo antes posible. 

Atentamente, 
Equipo internacional de Microsoft Docs

**Comment by CeciAc** [comment]
Hola, @UCdavidUC 

Gracias por sus comentarios. 

El equipo lingüístico ha revisado las sugerencias y las ha aceptado. Hemos implementado sus comentarios y los hemos publicado en los artículos actualizados del sitio de Docs en las siguientes páginas: https://docs.microsoft.com/es-mx/azure/vpn-gateway/vpn-gateway-about-vpngateways#V2V

Apreciamos su colaboración y le animamos a seguir enviándonos comentarios. 

Atentamente, 
Equipo internacional de Microsoft Docs

**Comment by UCdavidUC** [comment]
Hola @CeciAc 

Te agradezco por la pronta respuesta y la atención.

Saludos,
