### ISSUE TITLE
Auth access tokens for Storage REST Api

### ISSUE THREAD

**Issue by Tulkis** [MicrosoftDocs/azure-docs.es-es#309]
Hi all, 
We cannot find an example of auth headers creation. We are testing with the info in this doc:
https://docs.microsoft.com/en-us/rest/api/storageservices/authenticate-with-azure-active-directory
But we got errors like:
Invoke-RestMethod : AuthenticationFailedServer failed to authenticate the request. Make sure the 
value of Authorization header is formed correctly including the signature.
RequestId:*********************1a000000
Time:2019-03-06T13:08:53.0091863ZThe Date header in the request is incorrect.

Is there any doc wher we can find an example?
Regards,
Eduard.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 90a4bd03-9c86-4c9b-5834-c2966c2f3720
* Version Independent ID: a070cc29-15aa-c072-b90b-64c616ef51cc
* Content: [Autenticación del acceso a blobs y colas de Azure con Azure Active Directory (versión preliminar)](https://docs.microsoft.com/es-es/azure/storage/common/storage-auth-aad#feedback)
* Content Source: [articles/storage/common/storage-auth-aad.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/live/articles/storage/common/storage-auth-aad.md)
* Service: **storage**
* GitHub Login: @tamram
* Microsoft Alias: **tamram**

**Comment by CeciAc** [comment]
Hello, @Tulkis 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

**Comment by Tulkis** [comment]
Ok Ceciac,
I think I was talking about your documentation. Maybe I'm wrong. But still think there are a hole in it.
Bye

**Comment by Adam-Smith-MSFT** [comment]
@Tulkis There is a quick tutorial available in C# specific to Date Header, could you check this specific link to see if it helps: https://zimmergren.net/azure-storage-rest-api-authenticate-with-c/ 
Also were looking for samples in C# specifically or other languages ?

Thanks,
Adam

**Comment by tamram** [comment]
@Tulkis -

Here is a more complete example of how to construct the request with the Bearer scheme - does this help?

```
GET /container/file.txt
x-ms-version: 2017-11-09
Authorization: Bearer eyJ0eXAiO...V09ccgQ
User-Agent: PostmanRuntime/7.6.0
Accept: */*
Host: sampleoautheast2.blob.core.windows.net
accept-encoding: gzip, deflate



HTTP/1.1 200
status: 200
Content-Length: 28
Content-Type: text/plain
Content-MD5: dxG7IgOBzApXPcGHxGg5SA==
Last-Modified: Wed, 30 Jan 2019 07:21:32 GMT
Accept-Ranges: bytes
ETag: "0x8D686838F9E8BA7"
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 09f31964-e01e-00a3-8066-d4e6c2000000
x-ms-version: 2017-11-09
x-ms-creation-time: Wed, 29 Aug 2018 04:22:47 GMT
x-ms-lease-status: unlocked
x-ms-lease-state: available
x-ms-blob-type: BlockBlob
x-ms-server-encrypted: true
Date: Wed, 06 Mar 2019 21:50:50 GMT
Welcome to Azure Storage!!
```

**Comment by Tulkis** [comment]
> @Tulkis There is a quick tutorial available in C# specific to Date Header, could you check this specific link to see if it helps: https://zimmergren.net/azure-storage-rest-api-authenticate-with-c/
> Also were you looking for samples in C# specifically or other languages ?
> 
> Thanks,
> Adam

Hi Adam,
Thanks for the info, are there any examples building the request with Ps Invoke-WebRequest?
Regards

**Comment by Tulkis** [comment]
Hi again @tamram , the correct resource for this kind of api queries (storage) is "https://management.azure.com/" ? in the docu I see must be changed by "https://storage.azure.com/" but get errors like:
`{"error":{"code":"InvalidAuthenticationTokenAudience","message":"The access 
token has been obtained for wrong audience or resource 
'https://storage.azure.com/'. It should exactly match with one of the 
allowed audiences 'https://management.core.windows.net/','https://management
.core.wind`

**Comment by tamram** [comment]
@Tulkis - Can you tell me which API operation you are trying to call? (If possible, send me a link to the documentation page for that API operation, since the names are not always unique across Azure.)

**Comment by Tulkis** [comment]
Hello,
I am trying to retrieve a list of queues from a sta. Finally I got it. 
With this api call I get the correct token and can retrieve the list of queues:
`
#Get Api token
$resource = "https://storage.azure.com/"
$body = @{grant_type = "client_credentials"; resource = "$resource"; client_id = "$clientID"; client_secret = "$ClientSecret"}
$oauth = Invoke-RestMethod -Method Post -Uri "https://login.microsoftonline.com/$TenantID/oauth2/token?api-version=2018-03-28" -Body $body
$script:authHeaderST = @{'Authorization' = "$($oauth.token_type) $($oauth.access_token)"; 'x-ms-version' = '2018-03-28'; 'Date' = "$(get-date)"}
#Retrieve the list
Invoke-RestMethod -Uri 'https://**********.queue.core.windows.net?comp=list' -Headers $script:authHeader -Method Get
`
I suppose it is the correct way. It is right?
Regards,
Eduard

**Comment by tamram** [comment]
@Tulkis - Great! That looks good to me, and it sounds like it's working. 

If you have any more problems, feel free to open another issue and let us know.
