### ISSUE TITLE
Diferencia entre los 2 servicios

### ISSUE THREAD

**Issue by GoldenDiamonds** [MicrosoftDocs/azure-docs.es-es#334]
Me gustaria que explicaran la diferencia entre las instancias administradas de Azure SQL Database y las simples SQL Database, ya que no entiendo aun la diferencia.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ vinculación de problemas de GitHub.*

* ID: a73c2387-dd09-c1fe-a5bd-66ec176194b4
* Version Independent ID: d615c55b-caf1-5d78-072d-88614b8af9ff
* Content: [Azure Portal: Creación de una Instancia administrada de SQL](https://docs.microsoft.com/es-mx/azure/sql-database/sql-database-managed-instance-get-started?WT.mc_id=gallery#feedback)
* Content Source: [articles/sql-database/sql-database-managed-instance-get-started.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/live/articles/sql-database/sql-database-managed-instance-get-started.md)
* Service: **sql-database**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by CeciAc** [comment]
Hola, @GoldenDiamonds 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
