### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by alejoab321** [MicrosoftDocs/azure-docs.es-es#343]
Buenas, cuando le paso la ruta de la imagen por consola, me manda un error 404, yo seguí todos los pasos pero aún no me funciona.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 9d6a5f5a-4f15-366c-891a-5c953b4a4643
* Version Independent ID: 3090f05f-8557-3296-fda3-3cd28920556b
* Content: [Inicio rápido: Extracción de texto impreso (OCR) (REST, C#) - Azure Cognitive Services](https://docs.microsoft.com/es-es/azure/cognitive-services/computer-vision/quickstarts/csharp-print-text#feedback)
* Content Source: [articles/cognitive-services/Computer-vision/QuickStarts/CSharp-print-text.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/live/articles/cognitive-services/Computer-vision/QuickStarts/CSharp-print-text.md)
* Service: **cognitive-services**
* Sub-service: **computer-vision**
* GitHub Login: @PatrickFarley
* Microsoft Alias: **pafarley**

**Comment by CeciAc** [comment]
Hola, @alejoab321 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
