### ISSUE TITLE
Problemas con la creación de cluster

### ISSUE THREAD

**Issue by VaroJulio** [MicrosoftDocs/azure-docs.es-es#467]
Al ejecutar el script de poweshell para la creación del cluster se manifiesta el siguiente error:
DVERTENCIA: Access policy is not set. No user or application have access permission to use this vault. Please use Set
-AzKeyVaultAccessPolicy to set access policies.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 922b9c51-6a6d-1118-d2a2-6d485b222ce8
* Version Independent ID: 6874cc89-a1f8-addd-430f-a4d6b7f89ae8
* Content: [Creación de una aplicación contenedor de Windows de Service Fabric en Azure](https://docs.microsoft.com/es-es/azure/service-fabric/service-fabric-quickstart-containers#feedback)
* Content Source: [articles/service-fabric/service-fabric-quickstart-containers.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/service-fabric/service-fabric-quickstart-containers.md)
* Service: **service-fabric**
* GitHub Login: @aljo-microsoft
* Microsoft Alias: **aljo**

**Comment by CeciAc** [comment]
Hola, @VaroJulio 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs

**Comment by VaroJulio** [comment]
El error es sobre la documentación debido a que la sigo pero no funciona al ponerla en práctica.

**Comment by VaroJulio** [comment]
Al seguir al pie de la letra la guía de inicio rápido, ocurren errores durante la ejecución de los pasos.

**Comment by CeciAc** [comment]
Hola, @VaroJulio

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original. 
Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/MicrosoftDocs/azure-docs/issues/33093 
Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
