### ISSUE TITLE
Samples are no longer to choose

### ISSUE THREAD

**Issue by PauLiNuKS** [MicrosoftDocs/azure-docs.es-es#477]
Hi. 

I'm trying to create a Sql Data Warehouse with the sample AdventureWorksDW, but I don't see the option in Additional Settings when you create it. New updates of SQL Data Warehouse in Portal changed this. Is there another way? 

Thanks in advance.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 8e253528-7277-9f78-06e7-fff9f91e7a79
* Version Independent ID: 36ade0d7-ae89-da1e-2c74-65a4defefa84
* Content: [Tutorial: Carga de datos de taxis de Nueva York en Azure SQL Data Warehouse](https://docs.microsoft.com/es-es/azure/sql-data-warehouse/load-data-from-azure-blob-storage-using-polybase#feedback)
* Content Source: [articles/sql-data-warehouse/load-data-from-azure-blob-storage-using-polybase.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/sql-data-warehouse/load-data-from-azure-blob-storage-using-polybase.md)
* Service: **sql-data-warehouse**
* Sub-service: **load data**
* GitHub Login: @kevinvngo
* Microsoft Alias: **kevin**

**Comment by CeciAc** [comment]
Hello, @PauLiNuKS 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
