### ISSUE TITLE
Service Bus Queue body is null

### ISSUE THREAD

**Issue by infoTrainingym** [MicrosoftDocs/azure-docs.es-es#516]
When using Service Bus Queue handler, message arrive with body = null. From this Issue (https://github.com/Azure/azure-service-bus-dotnet/issues/123#issuecomment-470173196) Event grid must use old nuget version.

Adding 

```
using Microsoft.Azure.ServiceBus.InteropExtensions;

var body = message.GetBody<byte[]>();
```

 we could convert format to then new nuget version.

It should be notice in this page.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: aac7f75f-c324-8dab-76bb-ebedddd6f357
* Version Independent ID: 87467881-a215-78e8-b406-e83d558a7172
* Content: [Controladores de eventos de Azure Event Grid](https://docs.microsoft.com/es-es/azure/event-grid/event-handlers#feedback)
* Content Source: [articles/event-grid/event-handlers.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/event-grid/event-handlers.md)
* Service: **event-grid**
* GitHub Login: @spelluru
* Microsoft Alias: **spelluru**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #33945](https://github.com/MicrosoftDocs/azure-docs/issues/33945) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @infoTrainingym

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - XXX.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
