### ISSUE TITLE
Title Changed??

### ISSUE THREAD

**Issue by jorgeperona** [MicrosoftDocs/azure-docs.es-es#526]
I thinks there is an error in Synchronize files.
Synchronize a container to a local file system
In this case, the local file system becomes the source and the container is the destination

Synchronize a local file system to a container
In this case, the container becomes the source and the local file system is the destination.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: b646ce05-8744-6bd6-89d2-d830d27955e2
* Version Independent ID: 1c2226e5-be43-2d8e-a791-78570378b988
* Content: [Transferir datos desde o hacia Azure Blob storage mediante AzCopy v10](https://docs.microsoft.com/es-es/azure/storage/common/storage-use-azcopy-blobs#feedback)
* Content Source: [articles/storage/common/storage-use-azcopy-blobs.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/storage/common/storage-use-azcopy-blobs.md)
* Service: **storage**
* Sub-service: **common**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by CeciAc** [comment]
Hello, @jorgeperona 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @jorgeperona 
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
