### ISSUE TITLE
Observability of Spring Boot application in AKS

### ISSUE THREAD

**Issue by lpozo16** [MicrosoftDocs/azure-docs.es-es#533]
Hi. I find very interesting Application Insights. I wonder how can I get both application perfomance and end-to-end distributed tracing in Spring Boot applications. Equally, I am interested on application instrumentation.
I found several Microsoft documentation but I don't have clear how to get these goals (there are documents with different dates and I don't know which is the current version).
Also, I would like to trace Spring Boot application deployed in AKS by using standards like OpenTracing/OpenCensus or the future OpenTelemetry.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 90bab7a8-40fe-0736-c86c-a34ac821c006
* Version Independent ID: 6b872c6f-a8ca-f548-24d9-28d82e350b69
* Content: [Diagnóstico de problemas de rendimiento mediante Azure Application Insights](https://docs.microsoft.com/es-es/azure/azure-monitor/learn/tutorial-performance#feedback)
* Content Source: [articles/azure-monitor/learn/tutorial-performance.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/azure-monitor/learn/tutorial-performance.md)
* Service: **application-insights**
* GitHub Login: @mrbullwinkle
* Microsoft Alias: **mbullwin**

**Comment by CeciAc** [comment]
Hello, @lpozo16 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
