### ISSUE TITLE
duplicated title

### ISSUE THREAD

**Issue by daveRendon** [MicrosoftDocs/azure-docs.es-es#536]
[Escribir comentarios aquí]

Título Párrafo: Protección 
---

Título Párrafo: Seguridad (Corrección en vez de Protección)
---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ vinculación de problemas de GitHub.*

* ID: 7d29a8be-b039-09d0-7058-4eccd138cd80
* Version Independent ID: cbec794f-d3ce-6b8b-65a5-d7e893a81198
* Content: [Azure Management y Operations Management Suite (OMS)](https://docs.microsoft.com/es-mx/azure/azure-monitor/azure-management#feedback)
* Content Source: [articles/azure-monitor/azure-management.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/azure-monitor/azure-management.md)
* Service: **azure-monitor**
* GitHub Login: @bwren
* Microsoft Alias: **bwren**

**Comment by CeciAc** [comment]
Hola, @daveRendon 

Gracias por sus comentarios. 

Los revisaremos y nos pondremos en contacto con usted lo antes posible. 

Atentamente, 
Equipo internacional de Microsoft Docs

**Comment by CeciAc** [comment]
Hola, @daveRendon

Gracias por sus comentarios. 

El equipo lingüístico ha revisado las sugerencias y las ha aceptado. Hemos implementado sus comentarios y los hemos publicado en los artículos actualizados del sitio de Docs en las siguientes páginas: https://docs.microsoft.com/es-mx/azure/azure-monitor/azure-management

Apreciamos su colaboración y le animamos a seguir enviándonos comentarios. 

Atentamente, 
Equipo internacional de Microsoft Docs
