### ISSUE TITLE
Información incorrecta

### ISSUE THREAD

**Issue by fsolabenitez** [MicrosoftDocs/azure-docs.es-es#558]
La página indica lo siguiente: "Si el entorno tiene una instancia de Azure AD y una instancia de AD local, probablemente desee ampliar el alcance de la experiencia de inicio de sesión único a sus aplicaciones de línea de negocio (LOB) locales, recursos compartidos de archivos e impresoras." Cuando con Azure AD Join no es posible realizar SSO en unidades de ficheros en red local. 

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 0d912434-0693-e158-f371-51b010f8a533
* Version Independent ID: 51892e2c-8bd5-df84-28a1-548bbf0d8d96
* Content: [Funcionamiento del inicio de sesión único en recursos locales de dispositivos unidos a Azure AD](https://docs.microsoft.com/es-es/azure/active-directory/devices/azuread-join-sso#feedback)
* Content Source: [articles/active-directory/devices/azuread-join-sso.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/active-directory/devices/azuread-join-sso.md)
* Service: **active-directory**
* Sub-service: **devices**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by lichasu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #35044](https://github.com/MicrosoftDocs/azure-docs/issues/35044) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lichasu** [comment]
Hola, @fsolabenitez : 

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original. 
Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/MicrosoftDocs/azure-docs/issues/35044. 
Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
