### ISSUE TITLE
Some links in the main README.md are broken

### ISSUE THREAD

**Issue by DarryStonem** [MicrosoftDocs/azure-docs.es-es#57]
Some links are broken, mainly all related with the contributor guide, which files are not included, for example: 

- [nuestra guía de nombres de archivo](https://github.com/Microsoft/azure-docs.es-es/blob/live/contributor-guide/file-names-and-locations.md)

- [ Custom extensions used in our technical content](https://github.com/Microsoft/azure-docs.es-es/blob/live/contributor-guide/custom-markdown-extensions.md).

**Comment by SunnyDeng** [comment]
55391

**Comment by SunnyDeng** [comment]
@DarryStonem The fix is implemented. Thank you for the contribution! 
<Close the Issue>
