### ISSUE TITLE
Traducción de Dependency Injection

### ISSUE THREAD

**Issue by adiazcan** [MicrosoftDocs/azure-docs.es-es#603]
La traducción de dependency injection no es acertada, debería de ser "Inyección de Dependencia" y no "Inserción de dependencia"

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 5786402e-9d88-5de0-607a-1c2a143af006
* Version Independent ID: 15368d1c-b22e-7eb2-413f-cc0d41d2b909
* Content: [Uso de la inserción de dependencias en Azure Functions con .NET](https://docs.microsoft.com/es-es/azure/azure-functions/functions-dotnet-dependency-injection)
* Content Source: [articles/azure-functions/functions-dotnet-dependency-injection.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/azure-functions/functions-dotnet-dependency-injection.md)
* Service: **azure-functions**
* GitHub Login: @craigshoemaker
* Microsoft Alias: **cshoe**

**Comment by srvbpigh** [comment]
Hello, @adiazcan
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hola, @adiazcan

Gracias por sus comentarios lingüísticos.  

Después de revisarlos, el equipo lingüístico ha considerado que no cumplen con los criterios mínimos de aceptación porque [Gracias por sus comentarios. "insercción" es la traducción aprobada por Microsoft para "injection". ]

Apreciamos su colaboración y le animamos a seguir enviándonos comentarios.  

Atentamente, 

Equipo internacional de Microsoft Docs
