### ISSUE TITLE
Execute SSIS package: Set environment on Settings

### ISSUE THREAD

**Issue by Ameb** [MicrosoftDocs/azure-docs.es-es#614]
The dropdown for Environment on Settings is empty but we have some environments setup on the SSISDB. If we set environment path manually the execution fails with `Failed get environment reference.`

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 311ed7bd-e869-3e77-4601-235149e54c03
* Version Independent ID: 7f767d44-195c-d869-ab43-606feb470447
* Content: [Ejecución de paquetes SSIS con la actividad Ejecutar paquete de SSIS: Azure](https://docs.microsoft.com/es-es/azure/data-factory/how-to-invoke-ssis-package-ssis-activity#feedback)
* Content Source: [articles/data-factory/how-to-invoke-ssis-package-ssis-activity.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/data-factory/how-to-invoke-ssis-package-ssis-activity.md)
* Service: **data-factory**
* GitHub Login: @swinarko
* Microsoft Alias: **sawinark**

**Comment by srvbpigh** [comment]
Hello, @Ameb
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Ameb** [comment]
Found the solution on the MSDN forums:
https://social.msdn.microsoft.com/Forums/azure/en-US/06999c33-d26e-412c-b1bc-08914ca04e25/ssis-environment-path-info-incorrect?forum=AzureDataFactory

Please consider adding a reminder to the documentation that you should must add the references to the environments to the project first.

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #37363](https://github.com/MicrosoftDocs/azure-docs/issues/37363) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @Ameb

Thank you for your feedback.

I forwarded your suggestion to the en-US repo for its analysis: https://github.com/MicrosoftDocs/azure-docs/issues/37363

Kind regards,
Microsoft DOCS International Team
