### ISSUE TITLE
I can't find Auto-healing neither mitigate tab

### ISSUE THREAD

**Issue by sebainones** [MicrosoftDocs/azure-docs.es-es#646]
I have an App Service running on an Standard Service Plan.
I'm able to go to App Service Diagnostics and for instance drill-down on 5xx Errors.
But I can't find any way or option to see this Auto-Healing option neither the mitigate tab.
Could you point to the right direction or tell me what should I check in order to be able to access and set this auto-healing feature.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: fd8426b2-dbe5-9a46-4045-55cc26806641
* Version Independent ID: 99eef6e6-7978-1008-4d6f-a5ae566a6305
* Content: [Introducción a los diagnósticos de Azure App Service](https://docs.microsoft.com/es-es/azure/app-service/overview-diagnostics#feedback)
* Content Source: [articles/app-service/overview-diagnostics.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/app-service/overview-diagnostics.md)
* Service: **app-service**
* GitHub Login: @Jen7714
* Microsoft Alias: **jennile**

**Comment by srvbpigh** [comment]
Hello, @sebainones
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @sebainones

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
