### ISSUE TITLE
Como convertir string  a Newtonsoft.Json.Linq.JObject

### ISSUE THREAD

**Issue by Javier118** [MicrosoftDocs/azure-docs.es-es#652]
tengo problema  me da error en la  parte: LoginAsync(MobileServiceAuthenticationProvider.MicrosoftAccount, "{}"); 
diciendo no se puede convertir string a Newtonsoft.Json.Linq.JObject , estoy utlizando WTS(Windows Template studio) para Uwp C#.

¿Porque se produce este fallo?

`private async Task<bool> AuthenticateAsync()
        {
            string message;
            bool success = false;

            try
            {
                //Sign in using MicrosoftAccount

                user = await App.MobileService
                    .LoginAsync(MobileServiceAuthenticationProvider.MicrosoftAccount, "{}");
                message =
                    string.Format("You are now signed in - {0}", user.UserId);
               

                success = true;
            }
            catch(InvalidOperationException)
            {
                message = "You must log in. Login Required";

            }

            var dlg = new MessageDialog(message);
            dlg.Commands.Add(new UICommand("ok"));
            await dlg.ShowAsync();
            return success;

        }`

**Comment by srvbpigh** [comment]
Hello, @Javier118
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hola, @Javier118

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
