### ISSUE TITLE
OneDrive silent config feature link is not up to date

### ISSUE THREAD

**Issue by dariomws306** [MicrosoftDocs/azure-docs.es-es#654]
OneDrive silent config feature link should be update to send you to:
https://docs.microsoft.com/onedrive/use-silent-account-configuration

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 2010f5ac-1080-addd-1fb3-5b05db26c1f6
* Version Independent ID: 1aa18d6a-5846-7989-b844-fc8ad027921b
* Content: [Azure AD Connect: Inicio de sesión único de conexión directa](https://docs.microsoft.com/es-es/azure/active-directory/hybrid/how-to-connect-sso#feedback)
* Content Source: [articles/active-directory/hybrid/how-to-connect-sso.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/active-directory/hybrid/how-to-connect-sso.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by srvbpigh** [comment]
Hello, @dariomws306
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @dariomws306

Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/es-es/azure/active-directory/hybrid/how-to-connect-sso#feedback
We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
