### ISSUE TITLE
Error texto

### ISSUE THREAD

**Issue by GermanKuber** [MicrosoftDocs/azure-docs.es-es#655]
Los clústeres de AKAS pueden usar los  &gt;&gt; debería de ser ASK

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: d4af71a4-648e-580f-7e86-94ce05196de5
* Version Independent ID: 134b8ba0-b085-076a-d2e1-16d0ddff5586
* Content: [Tutorial de Kubernetes en Azure: Implementación de un clúster](https://docs.microsoft.com/es-es/azure/aks/tutorial-kubernetes-deploy-cluster#feedback)
* Content Source: [articles/aks/tutorial-kubernetes-deploy-cluster.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/aks/tutorial-kubernetes-deploy-cluster.md)
* Service: **container-service**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by srvbpigh** [comment]
Hello, @GermanKuber
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hola, @GermanKuber

Gracias por sus comentarios. 

El equipo lingüístico ha revisado las sugerencias y las ha aceptado. Hemos implementado sus comentarios y los hemos publicado en los artículos actualizados del sitio de Docs en las siguientes páginas: https://docs.microsoft.com/es-es/azure/aks/tutorial-kubernetes-deploy-cluster

Apreciamos su colaboración y le animamos a seguir enviándonos comentarios. 

Atentamente, 
Equipo internacional de Microsoft Docs
