### ISSUE TITLE
Help.

### ISSUE THREAD

**Issue by EmilioRuiz29** [MicrosoftDocs/azure-docs.es-es#671]
No puedo entrar a Minecraft.
[Escriba sus comentarios aquí]
No me deja entrar a Minecraft.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 8b52a210-1be6-4e5f-d95c-8ea7b87919ca
* Version Independent ID: 02a43ebb-7471-d7ff-4f7e-84c9f7a66326
* Content: [Copia de seguridad y recuperación con la aplicación Microsoft Authenticator: Azure Active Directory](https://docs.microsoft.com/es-es/azure/active-directory/user-help/user-help-auth-app-backup-recovery)
* Content Source: [articles/active-directory/user-help/user-help-auth-app-backup-recovery.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/active-directory/user-help/user-help-auth-app-backup-recovery.md)
* Service: **active-directory**
* Sub-service: **user-help**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by srvbpigh** [comment]
Hello, @EmilioRuiz29
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hola, @EmilioRuiz29

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs

**Comment by EmilioRuiz29** [comment]
No me deja entrar al juego de Minecraft.
