### ISSUE TITLE
Using --require with languageWorkers:node:arguments

### ISSUE THREAD

**Issue by rpcgen** [MicrosoftDocs/azure-docs.es-es#678]
Using languageWorkers:node:arguments it is possible to add nodejs options. So I can preload some required libraries (i.e. --require envdot/init), that seems to work. But I cannot preload files in my project to do some setup at the begining:

`
[03/10/2019 10:25:52] Error: Cannot find module './shared/preload'
[03/10/2019 10:25:52]     at Function.Module._resolveFilename (module.js:547:15)
[03/10/2019 10:25:52]     at Function.Module._load (module.js:474:25)
[03/10/2019 10:25:52]     at Module.require (module.js:596:17)
[03/10/2019 10:25:52]     at Function.Module._preloadModules (module.js:753:12)
[03/10/2019 10:25:52]     at preloadModules (bootstrap_node.js:475:38)
[03/10/2019 10:25:52]     at startup (bootstrap_node.js:188:9)
[03/10/2019 10:25:52]     at bootstrap_node.js:612:3
`

Is it possible to preload a module from a project files?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: b47363e3-c36f-0755-819c-26946013d673
* Version Independent ID: 197c63a1-9f72-1049-f27e-8c9c672ec472
* Content: [Referencia para desarrolladores de JavaScript para Azure Functions](https://docs.microsoft.com/es-es/azure/azure-functions/functions-reference-node#feedback)
* Content Source: [articles/azure-functions/functions-reference-node.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/azure-functions/functions-reference-node.md)
* Service: **azure-functions**
* GitHub Login: @ggailey777
* Microsoft Alias: **glenga**

**Comment by srvbpigh** [comment]
Hello, @rpcgen
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hello, @rpcgen 

Your contribution is highly appreciated. Yet, this feedback is related with product, please kindly log your suggestion by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.

We truly appreciate your contribution to our articles.

Microsoft DOCS International Team
