### ISSUE TITLE
Error in Copy Data Activity when source is empty of data

### ISSUE THREAD

**Issue by ffuentetech** [MicrosoftDocs/azure-docs.es-es#680]
I have a data factory, with a ForEach loop, in which I insert a Copy Data Activity that will be executed for every row in a table, taking values from columns in row.
The source of the Copy Data activity is an API Rest, using @items that come from the row columns, and are incrusted in the call to the API Rest. The call returns data that are copied to a sink. When it returns no data (because it hasn´t been generated from last call), the Copy Data activity fails and returns the following message error:
```
{
    "errorCode": "2200",
    "message": "Failure happened on 'Source' side. ErrorCode=UserErrorTypeInSchemaTableNotSupported,'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to get the type from schema table. This could be caused by missing Sql Server System CLR Types.,Source=Microsoft.DataTransfer.ClientLibrary,''Type=System.InvalidCastException,Message=Unable to cast object of type 'System.DBNull' to type 'System.Type'.,Source=Microsoft.DataTransfer.ClientLibrary,'",
    "failureType": "UserError",
    "target": "CopyFromQueryToTable"
}
```
The output of the activity is this:
```
{
    "dataRead": 338,
    "dataWritten": 0,
    "sourcePeakConnections": 2,
    "sinkPeakConnections": 2,
    "rowsRead": 1,
    "rowsCopied": 0,
    "rowsSkipped": 0,
    "copyDuration": 5,
    "throughput": 0.066,
    "redirectRowPath": "",
    "errors": [
        {
            "Code": 9074,
            "Message": "Failure happened on 'Source' side. ErrorCode=UserErrorTypeInSchemaTableNotSupported,'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Failed to get the type from schema table. This could be caused by missing Sql Server System CLR Types.,Source=Microsoft.DataTransfer.ClientLibrary,''Type=System.InvalidCastException,Message=Unable to cast object of type 'System.DBNull' to type 'System.Type'.,Source=Microsoft.DataTransfer.ClientLibrary,'",
            "EventType": 0,
            "Category": 5,
            "Data": {
                "FailureInitiator": "Source"
            },
            "MsgId": null,
            "ExceptionType": null,
            "Source": null,
            "StackTrace": null,
            "InnerEventInfos": []
        }],
    "effectiveIntegrationRuntime": "DefaultIntegrationRuntime (West Europe)",
    "usedDataIntegrationUnits": 4,
    "usedParallelCopies": 1,
    "executionDetails": [
        {
            "source": {
                "type": "RestService"
            },
            "sink": {
                "type": "AzureSqlDatabase",
                "region": "West Europe"
            },
            "status": "Failed",
            "start": "2019-10-03T14:46:28.1539346Z",
            "duration": 5,
            "usedDataIntegrationUnits": 4,
            "usedParallelCopies": 1,
            "detailedDurations": {
                "queuingDuration": 2,
                "preCopyScriptDuration": 0,
                "transferDuration": 3
  }}]}

```
This error has been solved finally with 2 steps previous the Copy Data activity:
- one Web activity that calls the API with the values of the @items 
- an If Condition activity that evaluates if the activity of previous step is empty: `(@bool(empty(activity('CalculateLenOfData').output.tables[0].rows)))`.

In my opinion, things with Copy Data could be more easy, not always there will be data to copy. We can expect that some times will bring no object, or an empty dataframe, table... In that cases **Copy Data activity shouldn´t block the execution of the following steps in the data factory**. This is a clear point of improvement for me.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 5f8f06db-58d4-75b9-f150-9a1b4767cf75
* Version Independent ID: 54c26e53-460a-2f6e-b4f2-86f1e8581435
* Content: [Actividad de copia en Azure Data Factory](https://docs.microsoft.com/es-es/azure/data-factory/copy-activity-overview#feedback)
* Content Source: [articles/data-factory/copy-activity-overview.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/data-factory/copy-activity-overview.md)
* Service: **data-factory**
* GitHub Login: @linda33wj
* Microsoft Alias: **jingwang**

**Comment by srvbpigh** [comment]
Hello, @ffuentetech
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hello, @ffuentetech 

Your contribution is highly appreciated. Yet, this feedback is related with product, please kindly log your suggestion by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.

We truly appreciate your contribution to our articles.

Microsoft DOCS International Team
