### ISSUE TITLE
Bad naming

### ISSUE THREAD

**Issue by PRodenasLechuga** [MicrosoftDocs/azure-docs.es-es#681]
Hello, 

This code line says:
   from azure.iot.device import IoTHubModuleClient

And afterwards is used like this: 
  def iothub_client_init():
    client = IoTHubDeviceClient.create_from_connection_string(CONNECTION_STRING)
    return client

It should be used this way:
  def iothub_client_init():
    client = IoTHubModuleClient.create_from_connection_string(CONNECTION_STRING)
    return client

I had a trouble today using this code and that's how I fixed it.

Best regards

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: ee954f99-9e57-d746-e504-445acf410291
* Version Independent ID: 9008125f-1961-6b08-8b8d-afe629a7354e
* Content: [Introducción a los dispositivos gemelos de Azure IoT Hub (Python)](https://docs.microsoft.com/es-es/azure/iot-hub/iot-hub-python-twin-getstarted#feedback)
* Content Source: [articles/iot-hub/iot-hub-python-twin-getstarted.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/iot-hub/iot-hub-python-twin-getstarted.md)
* Service: **iot-hub**
* GitHub Login: @robinsh
* Microsoft Alias: **robinsh**

**Comment by srvbpigh** [comment]
Hello, @PRodenasLechuga
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #40124](https://github.com/MicrosoftDocs/azure-docs/issues/40124) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lichasu** [comment]
Hello, @PRodenasLechuga 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/40124.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
