### ISSUE TITLE
Fix BatchServiceClient constructor example

### ISSUE THREAD

**Issue by dedreira** [MicrosoftDocs/azure-docs.es-es#692]
The BatchServiceClient constructor example has an error, according with:
https://docs.microsoft.com/en-us/python/api/azure-batch/azure.batch.batchserviceclient?view=azure-python
it should be:
    batch_client = BatchServiceClient(
    credentials,
    batch_url=BATCH_ACCOUNT_URL
)
instead of:
    batch_client = BatchServiceClient(
    credentials,
    base_url=BATCH_ACCOUNT_URL
)

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 726a2add-e28c-ab01-e63d-cc85bd1b961f
* Version Independent ID: 7e22d9ff-4d20-0709-78d5-9b39554fb126
* Content: [Uso de Azure Active Directory para autenticar soluciones de servicio de Azure Batch](https://docs.microsoft.com/es-es/azure/batch/batch-aad-auth#feedback)
* Content Source: [articles/batch/batch-aad-auth.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/batch/batch-aad-auth.md)
* Service: **batch**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by srvbpigh** [comment]
Hello, @dedreira
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @dedreira 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue #https://github.com/MicrosoftDocs/azure-docs/issues/45149
or this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
