### ISSUE TITLE
Información de costos asociados.

### ISSUE THREAD

**Issue by tnkmon** [MicrosoftDocs/azure-docs.es-es#694]
Muy buenas tardes pregunta general: El configurar este servicio automático genera algún costo adicional a medida que se consume? bien sea por almacenamiento o por la ejecución del mismo?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 51144539-a3a7-f7fa-1bc1-0d32bb85e9fd
* Version Independent ID: b01d33a0-4c5d-7ec4-8c2f-de4a940707dc
* Content: [Tutorial: Creación y administración de datos exportados desde Azure Cost Management](https://docs.microsoft.com/es-es/azure/cost-management/tutorial-export-acm-data#feedback)
* Content Source: [articles/cost-management/tutorial-export-acm-data.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/cost-management/tutorial-export-acm-data.md)
* Service: **cost-management-billing**
* GitHub Login: @bandersmsft
* Microsoft Alias: **banders**

**Comment by srvbpigh** [comment]
Hello, @tnkmon
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hola, @tnkmon:  

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original.  

Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/MicrosoftDocs/azure-docs/issues/45229.  

Apreciamos su contribución a nuestros artículos.   

Atentamente,  
Equipo internacional de Microsoft Docs
