### ISSUE TITLE
No es posible modificar la codificación base64 del body de mensajes deIOT Central

### ISSUE THREAD

**Issue by aimjarozas** [MicrosoftDocs/azure-docs.es-es#698]
He seguido las instrucciones para que elbody sea enviado en utf-8 y sigue enviando en base64.
iotc.sendTelemetry("{\"temp\": " 20"},{"contentType":"application/json","contentEncoding":"utf-8"}) y el sistema deja de enviar mensajes y se cae despues del primero.
Si saco el "contentEncoding": iotc.sendTelemetry("{\"temp\": " 20"},{"contentEncoding":"utf-8"}) el sistema envia los datos y no logro que contentEncoding quede en "SystemProperties", al revisar los datos con explorador de datos azure, el "Properties" tiene ContentEncoding:

{"EnqueuedTimeUtc":"2020-02-05T11:25:14.6600000Z","Properties":{"contentEncoding":"UTF-8"},"SystemProperties":{"connectionDeviceId":"c08bccb2-f98b-4970-8c23-64f4cad04778","connectionAuthMethod":"{\"scope\":\"device\",\"type\":\"sas\",\"issuer\":\"iothub\",\"acceptingIpFilterRule\":null}","connectionDeviceGenerationId":"637162428862774710","enqueuedTime":"2020-02-05T11:25:14.6600000Z"},"Body":"eyAidGVtcCI6IDQwLCAiYWNjZWxlcm9tZXRlclgiOiA2LCAiYWNjZWxlcm9tZXRlclkiOiA4LCAiYWNjZWxlcm9tZXRlcloiOiAxfQ=="}

Sin Embargo el dispositivo de prueba de azure si envia los datos con "contentEncoding" y "contentType" en el "SystemProperties":
{"EnqueuedTimeUtc":"2020-02-05T03:27:01.7930000Z","Properties":{},"SystemProperties":{"connectionDeviceId":"a6afea96-5c8a-4444-a3a1-39296559cf67","connectionAuthMethod":"{\"scope\":\"device\",\"type\":\"sas\",\"issuer\":\"iothub\",\"acceptingIpFilterRule\":null}","connectionDeviceGenerationId":"637147992846717051","contentType":"application/json","contentEncoding":"utf-8","enqueuedTime":"2020-02-05T03:27:01.7930000Z"},"Body":{"humidity":68.34782639005688,"temp":25.622457564514903,"pressure":751.5364002434342,"magnetometerX":613.8758265991783,"magnetometerY":-210.12340854852096,"magnetometerZ":56.43339961020797,"accelerometerX":201.75190023426285,"accelerometerY":-581.3482972370919,"accelerometerZ":427.12558126995737,"gyroscopeX":28.248091207506377,"gyroscopeY":-98.84944507438172,"gyroscopeZ":5.754910454919127}}

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 8be1f717-4e46-0a00-b4e3-823245834d3e
* Version Independent ID: 5c3f75ba-5eb2-0827-30ff-13c6cf95fc3f
* Content: [Consulta sobre el enrutamiento de mensajes de Azure IoT Hub](https://docs.microsoft.com/es-es/azure/iot-hub/iot-hub-devguide-routing-query-syntax#message-routing-query-based-on-message-body)
* Content Source: [articles/iot-hub/iot-hub-devguide-routing-query-syntax.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/iot-hub/iot-hub-devguide-routing-query-syntax.md)
* Service: **iot-hub**
* GitHub Login: @ash2017
* Microsoft Alias: **asrastog**

**Comment by srvbpigh** [comment]
Hello, @aimjarozas
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hola, @aimjarozas 

Agradecemos enormemente su colaboración. El equipo ha revisado sus comentarios y parece que el problema ya se ha registrado. 
Revise el problema # https://github.com/MicrosoftDocs/azure-docs/issues/47684

Por este motivo, se cerrará el problema, ya que está duplicado. 

Atentamente, 
Equipo internacional de Microsoft Docs
