### ISSUE TITLE
METADATA QnA- Case sensitive

### ISSUE THREAD

**Issue by LizMoreno** [MicrosoftDocs/azure-docs.es-es#699]
Hola, quisiera saber porque en la metadata para (name: value), no distingue las mayusculas de las minusculas?al entrenar la base de conocimiento, se ponen en minusculas.
ayuda por favor. Gracias!

**Comment by srvbpigh** [comment]
Hello, @LizMoreno
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/azure-docs #48068](https://github.com/MicrosoftDocs/azure-docs/issues/48068) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hola, @LizMoreno:  

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original.  

Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/MicrosoftDocs/azure-docs/issues/48068.  

Apreciamos su contribución a nuestros artículos.   

Atentamente,  
Equipo internacional de Microsoft Docs
