### ISSUE TITLE
Mi aporte a este documento cuando se ejecuta el comando: dotnet ef database update

### ISSUE THREAD

**Issue by salasjcruz** [MicrosoftDocs/azure-docs.es-es#702]
Marca el error:
No se pudo ejecutar porque no se encontr▒ el comando o archivo especificados.
Algunas de las posibles causas son:
  * Escribi▒ mal un comando dotnet integrado.
  * Intent▒ ejecutar un programa .NET Core, pero dotnet-ef no existe.
  * Tiene planeado ejecutar una herramienta global, pero no se encontr▒ un ejecutable con prefijo dotnet con este nombre en la RUTA DE ACCESO.
Solucion:
1.- Instalarlo, ejecutar el comando: 
dotnet tool install --global dotnet-ef
2.- Una vez instalado, ejecutar el comando de la siguiente manera:
dotnet-ef database update
luego ejecutar el comando
dotnet run
y listo ya se puede propbar la aplicacion de ejemplo en el navegador de internet

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 00961883-36eb-f736-b906-73d4c35e69b0
* Version Independent ID: 3a2fd493-9682-eedf-fad1-571b9391cd46
* Content: [Tutorial: ASP.NET Core con SQL Database](https://docs.microsoft.com/es-es/azure/app-service/app-service-web-tutorial-dotnetcore-sqldb#feedback)
* Content Source: [articles/app-service/app-service-web-tutorial-dotnetcore-sqldb.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/app-service/app-service-web-tutorial-dotnetcore-sqldb.md)

**Comment by srvbpigh** [comment]
Hello, @salasjcruz
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #49867](https://github.com/MicrosoftDocs/azure-docs/issues/49867) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hola, @salasjcruz:  

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original.  

Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/MicrosoftDocs/azure-docs/issues/49867.  

Apreciamos su contribución a nuestros artículos.   

Atentamente,  
Equipo internacional de Microsoft Docs
