### ISSUE TITLE
multiple pods example

### ISSUE THREAD

**Issue by jmorcar** [MicrosoftDocs/azure-docs.es-es#705]
I created a file share with this documentation, but when I created two or more deployment in kubernetes, yaml definition is different for each pod container to call the storageclass... storageClassName: azurefile-pod1 , storageClassName: azurefile-pod2 ... etc... because same name is failed, kubectl show error if your use always a name like : azurefile in storageClassName

------ Pod 1 --------
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypod1-pv
  namespace: &lt;mynamespace&gt;
  #comentario
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-pod1
  azureFile:
    secretName: filestorage-metrics-secret
    shareName: aksshare
------------------------ Pod 2 -------------------------
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypod2-pv
  namespace: &lt;mynamespace&gt;
  #comentario
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-pod2
  azureFile:
    secretName: filestorage-metrics-secret
    shareName: aksshare

I need an example with two pods or more.. thanks

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: d634c63a-6194-86a6-b522-3310812c81e8
* Version Independent ID: fa86da1e-9c86-88fe-170c-5e6aa9230b5f
* Content: [Creación de un volumen estático para varios pods en Azure Kubernetes Service (AKS)](https://docs.microsoft.com/es-es/azure/aks/azure-files-volume)
* Content Source: [articles/aks/azure-files-volume.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/aks/azure-files-volume.md)

**Comment by srvbpigh** [comment]
Hello, @jmorcar
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @jmorcar 

Your contribution is highly appreciated. Yet, this feedback is related with product, please kindly log your suggestion by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.

We truly appreciate your contribution to our articles.

Microsoft DOCS International Team
