### ISSUE TITLE
"Upgrade all clusters using Bash in Azure Command Shell" NOT WORKING

### ISSUE THREAD

**Issue by evmimagina** [MicrosoftDocs/azure-docs.es-es#706]
Hi,

When having multiple subscriptions under the same tenant that procedure doesn't work.

The "az login" command shows a message like;
"Cloud Shell is automatically authenticated under the initial account signed-in with. Run 'az login' only if you need to use a different account
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code ******* to authenticate."

And it stays there forever.

If I cancel the message and go to the next command there no error, BUT when I execute the last command, it shows the same message.

Could you please advice properly on this document?

Thanks,

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: fa9616f3-f92d-fc28-dd35-ce9b559d5130
* Version Independent ID: fb0ecd74-ea0d-1fb7-cace-536e587fef7c
* Content: [Actualización de Azure Monitor para contenedores para habilitar métricas](https://docs.microsoft.com/es-es/azure/azure-monitor/insights/container-insights-update-metrics)
* Content Source: [articles/azure-monitor/insights/container-insights-update-metrics.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/azure-monitor/insights/container-insights-update-metrics.md)

**Comment by srvbpigh** [comment]
Hello, @evmimagina
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #50718](https://github.com/MicrosoftDocs/azure-docs/issues/50718) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @evmimagina, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/50718. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
