### ISSUE TITLE
Github solicita usuario y password

### ISSUE THREAD

**Issue by jimmrl20** [MicrosoftDocs/azure-docs.es-es#710]
Al ejecutar la siguiente linea de comando en la raspberry, solicita usuario y contraseña, e ingresando la mia, no es posible clonar el repositorio:

git clone https://github.com/Azure-Samples/iot-hub-node-raspberrypi-client-app

Gracias de antemano por la ayuda

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: a57d05c9-562c-02a5-7ccd-b1b1bb7c8f0c
* Version Independent ID: 17ee094f-aee3-ca0c-959b-6380e4ea8b89
* Content: [Conexión de Raspberry Pi a Azure IoT Hub en la nube (Node.js)](https://docs.microsoft.com/es-es/azure/iot-hub/iot-hub-raspberry-pi-kit-node-get-started#feedback)
* Content Source: [articles/iot-hub/iot-hub-raspberry-pi-kit-node-get-started.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/iot-hub/iot-hub-raspberry-pi-kit-node-get-started.md)
* Service: **iot-hub**
* GitHub Login: @wesmc7777
* Microsoft Alias: **wesmc**

**Comment by srvbpigh** [comment]
Hello, @jimmrl20
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hola, @jimmrl20 

Gracias por su contribución. Sin embargo, estos comentarios están relacionados con el producto. Para registrar su sugerencia, haga clic en el botón «Proporcionar comentarios del producto» en la parte inferior de la página de DOCS. 

Si tiene algún comentario relacionado con la documentación, no dude en registrarlo a través de este canal. 

Apreciamos mucho su contribución a nuestros artículos. 

Equipo internacional de Microsoft DOCS
