### ISSUE TITLE
Installation steps on Linux need updating

### ISSUE THREAD

**Issue by gogux** [MicrosoftDocs/azure-docs.es-es#711]
The installation steps on Linux (Ubuntu) described at https://docs.microsoft.com/es-es/azure/azure-functions/functions-run-local?tabs=linux%2Ccsharp%2Cbash#install-the-azure-functions-core-tools need to be updated as the correct source is now &lt;&lt;deb [arch={arch}] https://packages.microsoft.com/ubuntu/{version}/prod {version nick} main&gt;&gt;.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: b2646ad4-34b7-fc5e-dcc9-d53a061df394
* Version Independent ID: bbff4fda-24e4-2b62-24b9-94cda5f53bed
* Content: [Uso de Azure Functions Core Tools](https://docs.microsoft.com/es-es/azure/azure-functions/functions-run-local?tabs=linux%2Ccsharp%2Cbash#install-the-azure-functions-core-tools)
* Content Source: [articles/azure-functions/functions-run-local.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/azure-functions/functions-run-local.md)
* GitHub Login: @carolinacmoravia

**Comment by srvbpigh** [comment]
Hello, @gogux
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #52323](https://github.com/MicrosoftDocs/azure-docs/issues/52323) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @gogux, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/52323. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
