### ISSUE TITLE
Comprobación adicional de permisos

### ISSUE THREAD

**Issue by GonzaloMurillo** [MicrosoftDocs/azure-docs.es-es#713]
El artículo es sumamente interesante. Como nota adicional, tan solo añadir, que debemos asegurarnos de que los permisos bajo nuestra instalación de wordpress son los correctos: 755 para los directorios bajo /var/www/html/wordpress y 644 para los ficheros.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 937f2d29-c487-7806-9021-a00bbb198303
* Version Independent ID: 5eecf6c4-ee12-a2e4-bb1e-0d78334f3c37
* Content: [Tutorial: implementación de LEMP en una máquina virtual Linux en Azure](https://docs.microsoft.com/es-es/azure/virtual-machines/linux/tutorial-lemp-stack#feedback)
* Content Source: [articles/virtual-machines/linux/tutorial-lemp-stack.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/virtual-machines/linux/tutorial-lemp-stack.md)
* Service: **virtual-machines-linux**
* GitHub Login: @cynthn
* Microsoft Alias: **cynthn**

**Comment by srvbpigh** [comment]
Hello, @GonzaloMurillo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hola, @GonzaloMurillo 

Apreciamos enormemente sus comentarios. Nos complace comprobar que su experiencia con la documentación cumple con sus expectativas.

Le recomendamos que proporcione comentarios para que podamos seguir mejorando su experiencia.

Atentamente,

Equipo internacional de Microsoft Docs
