### ISSUE TITLE
--encryption blob --  az storage account create: error: ambiguous option:

### ISSUE THREAD

**Issue by jmorcar** [MicrosoftDocs/azure-docs.es-es#714]
The documentation with param  "--encryption" is deprecated , must be changed to name "--encryption-services"
The correct command is discuss in this issue: https://github.com/Azure/azure-cli/issues/4220

Currently follow this page, the error is:
az storage account create: error: ambiguous option: --encryption could match --encryption-services, --encryption-key-type-for-table, --encryption-key-type-for-queue

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 4b7631ff-af60-5ab4-ac8b-d44f615308b3
* Version Independent ID: a661d456-bf6a-5061-391e-fe7b54b9a01f
* Content: [Inicio rápido: Creación de un blob con la CLI de Azure - Azure Storage](https://docs.microsoft.com/es-es/azure/storage/blobs/storage-quickstart-blobs-cli)
* Content Source: [articles/storage/blobs/storage-quickstart-blobs-cli.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/storage/blobs/storage-quickstart-blobs-cli.md)
* Service: **storage**
* Sub-service: **blobs**
* GitHub Login: @tamram
* Microsoft Alias: **tamram**

**Comment by srvbpigh** [comment]
Hello, @jmorcar
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #53163](https://github.com/MicrosoftDocs/azure-docs/issues/53163) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @jmorcar, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/53163. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
