### ISSUE TITLE
Problem with Power BI and REST API

### ISSUE THREAD

**Issue by tobydays** [MicrosoftDocs/azure-docs.es-es#716]
I try connect with POWER BI and I had the next issue:

Details: "The underlying connection was closed: An unexpected error occurred on a send."

![Config_Web_Error](https://user-images.githubusercontent.com/42366487/81110589-58fd4300-8ee1-11ea-9469-40e75ff4d51e.png)

And I was validate the config and is correct!

![Condig_Web_Postman_Ok](https://user-images.githubusercontent.com/42366487/81110622-66b2c880-8ee1-11ea-80d5-8c70f4e4061e.png)

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 9e6c6d2d-b1f8-86ed-4383-b3b4606d8046
* Version Independent ID: b58189d7-aaec-3487-a1c0-452726f940b3
* Content: [Realización de análisis de opiniones con Text Analytics API de REST - Azure Cognitive Services](https://docs.microsoft.com/es-es/azure/cognitive-services/text-analytics/how-tos/text-analytics-how-to-sentiment-analysis?tabs=version-3)
* Content Source: [articles/cognitive-services/text-analytics/how-tos/text-analytics-how-to-sentiment-analysis.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/cognitive-services/text-analytics/how-tos/text-analytics-how-to-sentiment-analysis.md)
* Service: **cognitive-services**
* Sub-service: **text-analytics**
* GitHub Login: @aahill
* Microsoft Alias: **aahi**

**Comment by srvbpigh** [comment]
Hello, @tobydays
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @tobydays 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/54133

We truly appreciate your contribution to our articles.  

Kind regards, 

Microsoft DOCS International Team
