### ISSUE TITLE
Error al momento de ejecutarlo localmente.

### ISSUE THREAD

**Issue by roanbaga** [MicrosoftDocs/azure-docs.es-es#717]
Cuando lo ejecutaba manualmente siempre me pedía que instalara el Azure Functions Core (aun cuando ya lo había hecho varias veces), y cuando llegaba al comando "func: hosts start" decía que no reconocía el comando "func". Después de dar mil vueltas encontré que solo funcionaba (en mi Windows 10) cuando se incluía en el path del sistema la ruta donde se había instalado el "func", en mi caso: "C:\Users\&lt;user&gt;\AppData\Roaming\npm\". Ahí ya todo funcionó, no volvió a pedir que instalar el Azure Functions Core y subió el servidor. Deberían incluir eso en el manual. Por otro lado cuando copia la URL no incluye el queryparam ?name=xxxxx, lo que hace que así simplemente falle. No sé porque no lo hace, en el ejemplo dice que debe hacerlo.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para la vinculación de problemas de docs.microsoft.com ➟ GitHub.*

* ID: 04c9d43d-5bd2-87c6-2ccf-0c65ef193760
* Version Independent ID: 6bf46ebc-481f-e4ef-b269-99bf99434601
* Content: [Creación de la primera función en Azure mediante Visual Studio Code](https://docs.microsoft.com/es-mx/azure/azure-functions/functions-create-first-function-vs-code?pivots=programming-language-java)
* Content Source: [articles/azure-functions/functions-create-first-function-vs-code.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/azure-functions/functions-create-first-function-vs-code.md)
* GitHub Login: @olprod

**Comment by srvbpigh** [comment]
Hello, @roanbaga
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #54332](https://github.com/MicrosoftDocs/azure-docs/issues/54332) via [**ZenHub**](https://www.zenhub.com/)
