### ISSUE TITLE
cname record worng.

### ISSUE THREAD

**Issue by genesisemmloh** [MicrosoftDocs/azure-docs.es-es#719]
[Escribir comentarios aquí]

no deberia haber apuntado el registro de cname hacia cdndocdemo1.azureedge.com  ?
por que lo apuntaron hacia contoso.azureedge.com ?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para la vinculación de problemas de docs.microsoft.com ➟ GitHub.*

* ID: b32fbbf3-178d-a0ef-7c3a-87df74a8eb16
* Version Independent ID: 2475b34a-88e8-5b45-723d-ee0a62230b8a
* Content: [Tutorial: Adición de un dominio personalizado a un punto de conexión de Azure CDN](https://docs.microsoft.com/es-mx/azure/cdn/cdn-map-content-to-custom-domain)
* Content Source: [articles/cdn/cdn-map-content-to-custom-domain.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/cdn/cdn-map-content-to-custom-domain.md)
* Service: **azure-cdn**
* GitHub Login: @asudbring
* Microsoft Alias: **allensu**

**Comment by srvbpigh** [comment]
Hello, @genesisemmloh
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #55082](https://github.com/MicrosoftDocs/azure-docs/issues/55082) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hola, @genesisemmloh:  

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original.  

Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/MicrosoftDocs/azure-docs/issues/55082.  

Apreciamos su contribución a nuestros artículos.   

Atentamente,  
Equipo internacional de Microsoft Docs
