### ISSUE TITLE
Create Compute instance for other users

### ISSUE THREAD

**Issue by aleixsd** [MicrosoftDocs/azure-docs.es-es#720]
Hello,

I would like to know if there is a way of creating Compute Instances for other users so they are able to use the jupyter in it. The idea is to have an administrator user who has permissions to create and delete compute instances and then the Data Science users who will develop inside Jupyter but without computes creation permissions.

Thanks,
Aleix Pujol

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 5431c3cc-af53-d7d5-4241-cf3d23d8689e
* Version Independent ID: 1b7eedd5-e934-aa15-d5c7-32ad82e45bbf
* Content: [¿Qué es una instancia de proceso de Azure Machine Learning? - Azure Machine Learning](https://docs.microsoft.com/es-es/azure/machine-learning/concept-compute-instance)
* Content Source: [articles/machine-learning/concept-compute-instance.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/machine-learning/concept-compute-instance.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @sdgilley
* Microsoft Alias: **sgilley**

**Comment by srvbpigh** [comment]
Hello, @aleixsd
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hello, @aleixsd , 

Your contribution is highly appreciated. Yet, this feedback is related with product, please kindly log your suggestion by using the button "Give Product Feedback" at the bottom of the DOCS page. 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles. 
Microsoft DOCS International Team
