### ISSUE TITLE
Perdí una cuenta de Mega en Authenticator

### ISSUE THREAD

**Issue by gerardoelcrack2** [MicrosoftDocs/azure-docs.es-es#721]
Cinfiguré la app para tener activa la verificación en dos pasos de mi cuenta de Mega e incluso active la copia de seguridad de la app, pero por motivos tuve que reinstalar la app e inicie sesión con mi cuenta de Microsoft y cargó todas mis cuentas exceptuando la de Mega, no sé que hacer y sino recupero la cuenta se eliminará mi cuenta de MEGA

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para la vinculación de problemas de docs.microsoft.com ➟ GitHub.*

* ID: 8b52a210-1be6-4e5f-d95c-8ea7b87919ca
* Version Independent ID: 02a43ebb-7471-d7ff-4f7e-84c9f7a66326
* Content: [Copia de seguridad y recuperación de cuentas con la aplicación Microsoft Authenticator: Azure AD](https://docs.microsoft.com/es-mx/azure/active-directory/user-help/user-help-auth-app-backup-recovery)
* Content Source: [articles/active-directory/user-help/user-help-auth-app-backup-recovery.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/active-directory/user-help/user-help-auth-app-backup-recovery.md)
* Service: **active-directory**
* Sub-service: **user-help**
* GitHub Login: @curtand
* Microsoft Alias: **curtand**

**Comment by srvbpigh** [comment]
Hello, @gerardoelcrack2
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by v-radelg** [comment]
Hola, @gerardoelcrack2 :

 

Gracias por su contribución. Sin embargo, estos comentarios están relacionados con el producto. Para registrar su sugerencia, haga clic en el botón «Proporcionar comentarios del producto» en la parte inferior de la página de DOCS.

 

Si tiene algún comentario relacionado con la documentación, no dude en registrarlo a través de este canal.

 

Apreciamos mucho su contribución a nuestros artículos.

 

Equipo internacional de Microsoft DOCS
