### ISSUE TITLE
Custom vistion train stucks

### ISSUE THREAD

**Issue by iAcisclo** [MicrosoftDocs/azure-docs.es-es#722]
my model training has been in the train phase for over 6 hours, only carries 10 images in total, what can be happening?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 8198ccf7-c499-c84b-6d54-e48a8fc4a150
* Version Independent ID: aae607bf-72be-59dd-32bc-be33039de820
* Content: [Inicio rápido: Creación de un clasificador (Custom Vision) - Azure Cognitive Services](https://docs.microsoft.com/es-es/azure/cognitive-services/custom-vision-service/getting-started-build-a-classifier)
* Content Source: [articles/cognitive-services/Custom-Vision-Service/getting-started-build-a-classifier.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/cognitive-services/Custom-Vision-Service/getting-started-build-a-classifier.md)
* Service: **cognitive-services**
* Sub-service: **custom-vision**
* GitHub Login: @PatrickFarley
* Microsoft Alias: **pafarley**

**Comment by srvbpigh** [comment]
Hello, @iAcisclo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @iAcisclo 

Your contribution is highly appreciated. Yet, this feedback is related with product, please kindly log your suggestion by using the button "Give Product Feedback" at the bottom of the DOCS page. 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles. 

Microsoft DOCS International Team
