### ISSUE TITLE
Temporary failure in name resolution

### ISSUE THREAD

**Issue by portacha** [MicrosoftDocs/azure-docs.es-es#724]
Hi I have a issues with the code on this page. my server return this:

<br />
<b>Warning</b>:  file_get_contents(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution in <b>/var/www/html/AzureText/script.php</b> on line <b>60</b><br />
<br />
<b>Warning</b>:  file_get_contents(https://********.cognitiveservices.azure.com/text/analytics/v2.1/languages): failed to open stream: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution in <b>/var/www/html/AzureText/script.php</b> on line <b>60</b><br />
null

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 30c000c8-09d4-b445-a60e-cb645a7dccfa
* Version Independent ID: de09ccb3-85fd-bf45-32b7-e47b1abb9e66
* Content: [Guía de inicio rápido: Uso de PHP para llamar a Text Analytics API - Azure Cognitive Services](https://docs.microsoft.com/es-es/azure/cognitive-services/text-analytics/quickstarts/php)
* Content Source: [articles/cognitive-services/text-analytics/quickstarts/php.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/cognitive-services/text-analytics/quickstarts/php.md)
* Service: **cognitive-services**
* Sub-service: **text-analytics**
* GitHub Login: @aahill
* Microsoft Alias: **aahi**

**Comment by srvbpigh** [comment]
Hello, @portacha
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #55793](https://github.com/MicrosoftDocs/azure-docs/issues/55793) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @portacha, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/55793. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
