### ISSUE TITLE
"Graph" should be translated into "Grafo" instead of "Gráfico" in Spanish

### ISSUE THREAD

**Issue by javierglozano** [MicrosoftDocs/azure-docs.es-es#74]
Hi guys,

The right translation of the English word "graph" into Spanish (in the context of Cosmos DB) should be "grafo" not "gráfico". In Spanish "gráfico" refers to a chart instead to a connected collection of vertex (that's a "grafo") Reference : https://es.wikipedia.org/wiki/Grafo

**Comment by SunnyDeng** [comment]
55392

**Comment by SunnyDeng** [comment]
55392 was fixed at 8/24, TM was updated. the issue should not repro.
