### ISSUE TITLE
Pricing for WebHook connector

### ISSUE THREAD

**Issue by MunozVictor** [MicrosoftDocs/azure-docs.es-es#752]
I'm looking for the specific pricing for the web hook connector for Logic Apps,

- When the connector it's waiting callback
- When action it's invoked.

Thanks.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 43127bca-9e45-47bc-8164-f7c0bd670fe3
* Version Independent ID: 559964eb-d2eb-93fc-fd6a-8a8f63a3232e
* Content: [Espera y respuesta a eventos - Azure Logic Apps](https://docs.microsoft.com/es-es/azure/connectors/connectors-native-webhook)
* Content Source: [articles/connectors/connectors-native-webhook.md](https://github.com/MicrosoftDocs/azure-docs.es-es/blob/master/articles/connectors/connectors-native-webhook.md)
* Service: **logic-apps**
* GitHub Login: @ecfan
* Microsoft Alias: **estfan**

**Comment by ecfan** [comment]
Hi @MunozVictor, you can find the pricing information here:

* [Pricing model for Azure Logic Apps](https://docs.microsoft.com/azure/logic-apps/logic-apps-pricing): General info how billing works for Azure Logic Apps
* [Logic Apps pricing](https://azure.microsoft.com/pricing/details/logic-apps/): Specific rate details based on your logic app's region

**Comment by ecfan** [comment]
Adding @jonfancey for additional explanation

**Comment by SunnyDeng** [comment]
Thank you @MunozVictor for the feedback. I've moved this issue to EN repo as @ecfan request. Please kindly check the respond through https://github.com/MicrosoftDocs/azure-docs/issues/65839.
